dist: trusty
language: go

go:
  - 1.12.x
branches:
  only:
    - /^development\/v.*$/
    - /^release\/v.*$/
    - /^feature\/.*$/
    - /^v.*$/

# env:
#   - GOMAXPROCS=4 GO111MODULE=on
git:
  submodules: true

# install:
#   - go get golang.org/x/crypto/pkcs12
#   - go get github.com/pkg/errors
#   - go get github.com/hashicorp/terraform@v0.11.13
#   - go mod tidy
#   - go mod vendor
#   - go get github.com/DimensionDataResearch/go-dd-cloud-compute@development/v2.0
# before_script:
#   - git submodule update

script:
  - go test -v ./...
before_deploy:
  - export TRAVIS_TAG="v1.0.1"
#   - export TRAVIS_COMMIT="dcdf8bd8af8d0144fb830cdccbf4ad048d946a9c"
  - git tag $TRAVIS_TAG 
  #- echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
  #- git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"
deploy:
  provider: releases
  api_key:
    secure: YeP33TYT4M9lINGBZscSBRUpAQWJNz/bQS0oaPdvUklF5noKccUsVUgMbtqy7VxIYes8UsVQTtiOExMRVq2j6Gcz7oiLpG5stmFERY7cZG4SKI9Q4lTMcZZZFn5IO0FP4+WF36ztuOGXXi8y40nlYqq/A2NS93C1soZ9Wb/nihmhGIoBOIBo9yfyt7n/qTiVneMeDs66nzc8K3GmzaP9vA2ydWprSrzIDdUYW474pCj7/JzXN1S/3ACZtA7Yt6BQujaacZOhjIjPh/GIYscN5R1t1q0VuFC4AFpxKk52syLNUuf7t25+1simPCS+BhL8BnqsPeXyuJc1ZwHfCmaZ8anqBX75Dsdy+3yQBqHDOfR8nRRrA3YZtViXzeAc+ki6zlHmbc717rxa8XyWecHwBkI/8c4xiKkOOf1DOfv+M/u1VvOz0Y+1stkg6VCwXVAqMAu3YIlHRdl0HyIZx9myXLo5qHLSsvCNzSwp5zdjm1+6KHmY5rTTSOdi9R1yHUGQK+aSrVb2bf5cX6ONCEPMgLnrHCaMSy/+TfX3/0JO69XGOEWiIMXcnRvjDjBIOaNNrnSwkXIGe0sq+96IcSCZj6E0SVbhLuWS6fKTkpn5mV1iKqkNPIGUD++a8BxC09DDnE0+9vbMFQGPuWoEaZ68DDs5oP2RGlYDzmlIGZLfsIw=
  file_glob: true
  file: _bin/.*
  draft: true
  skip_cleanup: 'true'
#   tag_name: $TRAVIS_TAG
#   target_commitish: $TRAVIS_COMMIT
#   overwrite: true
on:
  tags: true
#     repo: samuelchong/travis_test
#     branches:
#       only:
#         - /master
#         - /^development\/v.*$/
#         - /^release\/v.*$/
#         - /^feature\/.*$/
#         - /^v.*$/
  
